billing_account_name = "bca92218-bdfe-407e-b2c0-02ef02b3b6f8:333013a0-57ae-4229-82b3-b3cd70239eb2_2019-05-31"
billing_profile_name = "XU5N-S6UC-BG7-PGB"
invoice_section_name = "O3O3-76BD-PJA-PGB"
mg_id = "atlz"
workload_type = "Production"
