name: "01-Vending-CD"
on:
  push:
    #types:
    #  - opened
    #  - reopened
    #  - synchronize
    branches:
      - main
      - develop
    paths:
      - "01-vending/**"
  workflow_dispatch:
    inputs:
      terraform_action:
        description: "Terraform Action to Perform"
        required: true
        default: "apply"
        type: choice
        options:
          - "apply"
          - "destroy"

jobs:
  validate_and_plan:
    name: "01-Vending-CD"
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/template-cd.yaml
    with:
      gh_workflow: 01-vending
    secrets: inherit
